resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/smkell/concourse-quickstart.git

jobs:
- name: hello-world-job
  plan:
  # Add a get step referencing the resource
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
        - name: repo
      run:
        path: cat
        args: ["repo/README.md"]